version: "3.7"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
