apiVersion: batch/v1
kind: Job
metadata:
  name: demo-migrate
  labels:
    app.kubernetes.io/name: demo-migrate
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-migrate
    spec:
      containers:
        - name: demo-migrate
          image: murny/demo:latest
          imagePullPolicy: IfNotPresent
          command: ["bundle exec rails db:migrate"]
          envFrom:
            - configMapRef:
                name: demo
      restartPolicy: Never
